### ISSUE TITLE
Nodejs not exists

### ISSUE THREAD

**Issue by Mama59** [mk-pmb/yaml-lint-all-recursive-node#2]
On my computer, when i install nodejs, it's named node, so i need to renamed nodejs to node on your code have you any solution please ?

**Comment by mk-pmb** [comment]
Which OS/file system? Where possible, I recommend adding a symlink `nodejs` &rarr; `node`.
(Linux: `sudo ln --symbolic --verbose --no-target-directory -- node /usr/bin/nodejs`)
I'm considering adding automatic fallback though. (Update: Added in 0.1.4.)
